export const ACCEPT_CONFIG = {
  image: [".png", ".jpg", ".jpeg", ".gif", ".bmp", ".webp"],
  video: [
    ".mp4",
    ".rmvb",
    ".mkv",
    ".wmv",
    ".flv",
    ".avi",
    ".m3u8",
    ".swf",
    ".3gp",
    ".flv",
  ],
  audio: [".mp3", ".wav", ".wma", ".ogg", ".aac", ".flac"],
  document: [
    ".doc",
    ".docx",
    ".xls",
    ".xlsx",
    ".ppt",
    ".pptx",
    ".pdf",
    ".txt",
    ".tif",
    ".tiff",
    ".rar",
    ".zip",
    ".pages",
    ".epub",
    ".pdf",
    ".numbers",
    ".csv",
    ".keynote",
  ],
  getAll() {
    return [...this.image, ...this.video, ...this.document];
  },
};
